spring:
  application:
    name: invoices-service
  config:
    import: configserver:http://config-server:8888


---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
